groups:
- name: test_alerts
  rules:
  - alert: TestAlert
    expr: vector(1)  # 항상 1을 반환하여 알림 발생
    for: 1s
    labels:
      severity: warning
    annotations:
      summary: "This is a test alert"
      description: "Testing alert functionality"