# Generated by Django 5.1.1 on 2024-09-08 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ball_x', models.FloatField(default=0)),
                ('ball_y', models.FloatField(default=0)),
                ('ball_speed', models.FloatField(default=10)),
                ('ball_xvec', models.FloatField(default=0)),
                ('ball_yvec', models.FloatField(default=0)),
                ('bar0_x', models.FloatField(default=0)),
                ('bar0_y', models.FloatField(default=0)),
                ('bar0_move', models.IntegerField(default=0)),
                ('bar1_x', models.FloatField(default=0)),
                ('bar1_y', models.FloatField(default=0)),
                ('bar1_move', models.IntegerField(default=0)),
                ('score0', models.IntegerField(default=0)),
                ('score1', models.IntegerField(default=0)),
                ('serve', models.IntegerField(default=0)),
                ('game_state', models.CharField(default='start')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='remoteGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pingpong.gamesession')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
