# Generated by Django 5.1.1 on 2024-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegamesession',
            name='player1_name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='remotegamesession',
            name='player2_name',
            field=models.CharField(default=''),
        ),
    ]
